// Local ingredient database — values per 100g — source: USDA FoodData Central
const FOODS_DB = [

  // ── PROTÉINES ANIMALES ──────────────────────────────────────────────────
  { name: "Oeuf entier cru",          aliases: ["oeuf","oeufs","egg","eggs","oeuf entier"],
    kcal:155, protein:13.0, fat:11.0, carbs:1.1,  fiber:0.0, salt:0.4, category:"Oeufs & Produits laitiers" },
  { name: "Blanc d'oeuf cru",         aliases: ["blanc d'oeuf","blanc oeuf","albumen","egg white"],
    kcal:52,  protein:10.9, fat:0.2,  carbs:0.7,  fiber:0.0, salt:0.4, category:"Oeufs & Produits laitiers" },
  { name: "Jaune d'oeuf cru",         aliases: ["jaune d'oeuf","jaune oeuf","egg yolk"],
    kcal:322, protein:15.9, fat:26.5, carbs:3.6,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },

  { name: "Poulet (sein, cuit)",       aliases: ["poulet","chicken","blanc poulet","sein poulet","filet poulet","poitrine poulet"],
    kcal:165, protein:31.0, fat:3.6,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Poulet (cuisse, cuit)",     aliases: ["cuisse poulet","pilon poulet","poulet cuisse"],
    kcal:177, protein:24.0, fat:8.2,  carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },
  { name: "Viande hachée boeuf 5%",   aliases: ["viande hachee","viande hachée","boeuf haché","boeuf hache","steak haché","steak hache","ground beef"],
    kcal:137, protein:21.4, fat:5.0,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Viande hachée boeuf 15%",  aliases: ["boeuf 15","viande hachee 15","viande hachée 15%","hamburger"],
    kcal:215, protein:18.0, fat:15.0, carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },
  { name: "Boeuf (rumsteak, cuit)",   aliases: ["boeuf","beef","steak","rumsteak","entrecote","entrecôte"],
    kcal:207, protein:26.3, fat:10.5, carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Porc (filet, cuit)",        aliases: ["porc","pork","filet porc","côte porc","cote porc"],
    kcal:143, protein:26.0, fat:3.5,  carbs:0.0,  fiber:0.0, salt:0.1, category:"Viandes & Poissons" },
  { name: "Dinde (sein, cuite)",       aliases: ["dinde","turkey","escalope dinde","blanc dinde"],
    kcal:157, protein:29.9, fat:3.2,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Agneau (côtelette, cuit)",  aliases: ["agneau","lamb","côtelette agneau"],
    kcal:294, protein:24.5, fat:20.7, carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },

  { name: "Saumon (cuit)",             aliases: ["saumon","salmon","filet saumon"],
    kcal:208, protein:20.4, fat:13.4, carbs:0.0,  fiber:0.0, salt:0.1, category:"Viandes & Poissons" },
  { name: "Thon (en boîte, au naturel)",aliases: ["thon","tuna","thon naturel","thon boite","thon boîte"],
    kcal:116, protein:25.5, fat:1.0,  carbs:0.0,  fiber:0.0, salt:0.5, category:"Viandes & Poissons" },
  { name: "Cabillaud (cuit)",          aliases: ["cabillaud","cod","morue","colin"],
    kcal:105, protein:22.8, fat:0.9,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Crevettes (cuites)",        aliases: ["crevettes","shrimp","gambas","crevette"],
    kcal:99,  protein:23.7, fat:0.3,  carbs:0.2,  fiber:0.0, salt:1.3, category:"Viandes & Poissons" },
  { name: "Sardines (en boîte, huile)",aliases: ["sardines","sardine"],
    kcal:208, protein:24.6, fat:11.5, carbs:0.0,  fiber:0.0, salt:0.8, category:"Viandes & Poissons" },
  { name: "Maquereau (cuit)",          aliases: ["maquereau","mackerel"],
    kcal:262, protein:23.8, fat:17.8, carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },

  // ── PRODUITS LAITIERS ───────────────────────────────────────────────────
  { name: "Lait entier (3,5%)",        aliases: ["lait","milk","lait entier","lait 3","whole milk"],
    kcal:61,  protein:3.2,  fat:3.3,  carbs:4.7,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Lait écrémé (0,1%)",        aliases: ["lait ecreme","lait écrémé","lait 0","skim milk"],
    kcal:34,  protein:3.4,  fat:0.1,  carbs:4.9,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Fromage blanc 0%",          aliases: ["fromage blanc","faisselle","fromage blanc 0"],
    kcal:47,  protein:8.0,  fat:0.2,  carbs:3.5,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Yaourt nature entier",      aliases: ["yaourt","yogurt","yaourt nature","yoghurt"],
    kcal:61,  protein:3.5,  fat:3.3,  carbs:4.7,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Skyr nature",               aliases: ["skyr"],
    kcal:60,  protein:11.0, fat:0.2,  carbs:4.0,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Emmental",                  aliases: ["emmental","emmenthal","gruyere","gruyère"],
    kcal:382, protein:28.6, fat:29.7, carbs:0.5,  fiber:0.0, salt:0.7, category:"Oeufs & Produits laitiers" },
  { name: "Mozzarella",                aliases: ["mozzarella"],
    kcal:280, protein:28.0, fat:17.1, carbs:2.2,  fiber:0.0, salt:0.6, category:"Oeufs & Produits laitiers" },
  { name: "Cottage cheese",            aliases: ["cottage","cottage cheese"],
    kcal:98,  protein:11.1, fat:4.3,  carbs:3.4,  fiber:0.0, salt:0.4, category:"Oeufs & Produits laitiers" },
  { name: "Beurre",                    aliases: ["beurre","butter"],
    kcal:717, protein:0.9,  fat:81.1, carbs:0.1,  fiber:0.0, salt:0.6, category:"Oeufs & Produits laitiers" },
  { name: "Crème fraîche entière",     aliases: ["creme fraiche","crème fraîche","creme","crème"],
    kcal:292, protein:2.5,  fat:30.0, carbs:2.7,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },

  // ── FÉCULENTS & CÉRÉALES ────────────────────────────────────────────────
  { name: "Riz blanc (cru)",           aliases: ["riz","rice","riz blanc","riz cru"],
    kcal:365, protein:7.1,  fat:0.7,  carbs:80.0, fiber:1.3, salt:0.0, category:"Féculents & Céréales" },
  { name: "Riz blanc (cuit)",          aliases: ["riz cuit","riz blanc cuit"],
    kcal:130, protein:2.7,  fat:0.3,  carbs:28.2, fiber:0.4, salt:0.0, category:"Féculents & Céréales" },
  { name: "Pâtes (crues)",             aliases: ["pates","pâtes","pasta","spaghetti","penne","fusilli","pate"],
    kcal:371, protein:13.0, fat:1.5,  carbs:74.7, fiber:3.2, salt:0.0, category:"Féculents & Céréales" },
  { name: "Pâtes (cuites)",            aliases: ["pates cuites","pâtes cuites","pasta cuite","spaghetti cuit"],
    kcal:131, protein:5.0,  fat:1.1,  carbs:25.0, fiber:1.8, salt:0.0, category:"Féculents & Céréales" },
  { name: "Flocons d'avoine",          aliases: ["avoine","flocons avoine","oatmeal","oats","porridge","muesli"],
    kcal:389, protein:16.9, fat:6.9,  carbs:66.3, fiber:10.6,salt:0.0, category:"Féculents & Céréales" },
  { name: "Quinoa (cuit)",             aliases: ["quinoa"],
    kcal:120, protein:4.4,  fat:1.9,  carbs:21.3, fiber:2.8, salt:0.0, category:"Féculents & Céréales" },
  { name: "Pain blanc",               aliases: ["pain","bread","baguette","pain blanc","pain de mie"],
    kcal:265, protein:9.0,  fat:3.2,  carbs:49.0, fiber:2.7, salt:1.1, category:"Féculents & Céréales" },
  { name: "Pain complet",             aliases: ["pain complet","pain integral","pain intégral","whole wheat bread"],
    kcal:247, protein:13.0, fat:3.4,  carbs:41.0, fiber:7.0, salt:0.9, category:"Féculents & Céréales" },
  { name: "Pomme de terre (cuite)",    aliases: ["pomme de terre","pommes de terre","potato","patate","pomme terre"],
    kcal:87,  protein:1.9,  fat:0.1,  carbs:20.1, fiber:1.8, salt:0.0, category:"Féculents & Céréales" },
  { name: "Patate douce (cuite)",      aliases: ["patate douce","sweet potato","yam"],
    kcal:90,  protein:2.0,  fat:0.1,  carbs:20.7, fiber:3.3, salt:0.0, category:"Féculents & Céréales" },
  { name: "Lentilles (cuites)",        aliases: ["lentilles","lentille","lentils"],
    kcal:116, protein:9.0,  fat:0.4,  carbs:20.1, fiber:7.9, salt:0.0, category:"Légumineuses" },
  { name: "Pois chiches (cuits)",      aliases: ["pois chiches","pois chiche","chickpeas","poids chiches"],
    kcal:164, protein:8.9,  fat:2.6,  carbs:27.4, fiber:7.6, salt:0.0, category:"Légumineuses" },
  { name: "Haricots rouges (cuits)",   aliases: ["haricots","haricots rouges","kidney beans","haricot rouge"],
    kcal:127, protein:8.7,  fat:0.5,  carbs:22.8, fiber:7.4, salt:0.0, category:"Légumineuses" },

  // ── LÉGUMES ─────────────────────────────────────────────────────────────
  { name: "Brocoli (cuit)",            aliases: ["brocoli","broccoli","brocolis"],
    kcal:35,  protein:2.4,  fat:0.4,  carbs:7.2,  fiber:3.3, salt:0.0, category:"Légumes" },
  { name: "Épinards (crus)",           aliases: ["epinards","épinards","spinach","epinard","épinard"],
    kcal:23,  protein:2.9,  fat:0.4,  carbs:3.6,  fiber:2.2, salt:0.1, category:"Légumes" },
  { name: "Carotte (crue)",            aliases: ["carotte","carottes","carrot"],
    kcal:41,  protein:0.9,  fat:0.2,  carbs:9.6,  fiber:2.8, salt:0.1, category:"Légumes" },
  { name: "Tomate",                    aliases: ["tomate","tomates","tomato"],
    kcal:18,  protein:0.9,  fat:0.2,  carbs:3.9,  fiber:1.2, salt:0.0, category:"Légumes" },
  { name: "Courgette (cuite)",         aliases: ["courgette","courgettes","zucchini"],
    kcal:17,  protein:1.2,  fat:0.3,  carbs:3.1,  fiber:1.0, salt:0.0, category:"Légumes" },
  { name: "Concombre",                 aliases: ["concombre","cucumber"],
    kcal:15,  protein:0.7,  fat:0.1,  carbs:3.6,  fiber:0.5, salt:0.0, category:"Légumes" },
  { name: "Poivron rouge",             aliases: ["poivron","poivrons","pepper","poivron rouge"],
    kcal:31,  protein:1.0,  fat:0.3,  carbs:6.0,  fiber:2.1, salt:0.0, category:"Légumes" },
  { name: "Champignon blanc",          aliases: ["champignon","champignons","mushroom","champignons de paris"],
    kcal:22,  protein:3.1,  fat:0.3,  carbs:3.3,  fiber:1.0, salt:0.0, category:"Légumes" },

  // ── FRUITS ──────────────────────────────────────────────────────────────
  { name: "Banane",                    aliases: ["banane","banana"],
    kcal:89,  protein:1.1,  fat:0.3,  carbs:22.8, fiber:2.6, salt:0.0, category:"Fruits" },
  { name: "Pomme",                     aliases: ["pomme","apple"],
    kcal:52,  protein:0.3,  fat:0.2,  carbs:13.8, fiber:2.4, salt:0.0, category:"Fruits" },
  { name: "Orange",                    aliases: ["orange"],
    kcal:47,  protein:0.9,  fat:0.1,  carbs:11.8, fiber:2.4, salt:0.0, category:"Fruits" },
  { name: "Myrtilles",                 aliases: ["myrtilles","myrtille","blueberry","blueberries"],
    kcal:57,  protein:0.7,  fat:0.3,  carbs:14.5, fiber:2.4, salt:0.0, category:"Fruits" },
  { name: "Fraises",                   aliases: ["fraise","fraises","strawberry"],
    kcal:32,  protein:0.7,  fat:0.3,  carbs:7.7,  fiber:2.0, salt:0.0, category:"Fruits" },
  { name: "Avocat",                    aliases: ["avocat","avocado"],
    kcal:160, protein:2.0,  fat:14.7, carbs:8.5,  fiber:6.7, salt:0.0, category:"Fruits" },

  // ── MATIÈRES GRASSES & NOIX ─────────────────────────────────────────────
  { name: "Huile d'olive",             aliases: ["huile olive","huile d'olive","olive oil"],
    kcal:884, protein:0.0,  fat:100.0,carbs:0.0,  fiber:0.0, salt:0.0, category:"Matières grasses" },
  { name: "Huile de coco",             aliases: ["huile coco","huile de coco","coconut oil"],
    kcal:862, protein:0.0,  fat:100.0,carbs:0.0,  fiber:0.0, salt:0.0, category:"Matières grasses" },
  { name: "Amandes",                   aliases: ["amandes","amande","almond","almonds"],
    kcal:579, protein:21.2, fat:49.9, carbs:21.6, fiber:12.5,salt:0.0, category:"Noix & Graines" },
  { name: "Noix",                      aliases: ["noix","walnut","walnuts"],
    kcal:654, protein:15.2, fat:65.2, carbs:13.7, fiber:6.7, salt:0.0, category:"Noix & Graines" },
  { name: "Noix de cajou",             aliases: ["cajou","cashew","noix de cajou"],
    kcal:553, protein:18.2, fat:43.9, carbs:30.2, fiber:3.3, salt:0.0, category:"Noix & Graines" },
  { name: "Beurre de cacahuète",       aliases: ["beurre cacahuete","beurre de cacahuète","peanut butter","cacahuete","cacahuète"],
    kcal:588, protein:25.1, fat:50.4, carbs:20.1, fiber:5.9, salt:0.4, category:"Noix & Graines" },
  { name: "Graines de chia",           aliases: ["chia","graines chia","chia seeds"],
    kcal:486, protein:16.5, fat:30.7, carbs:42.1, fiber:34.4,salt:0.0, category:"Noix & Graines" },

  // ── PROTÉINES EN POUDRE ─────────────────────────────────────────────────
  { name: "Whey protéine (standard)",  aliases: ["whey","proteine poudre","whey protein","proteines","whey isolat"],
    kcal:380, protein:75.0, fat:5.0,  carbs:10.0, fiber:0.0, salt:0.5, category:"Compléments" },
  { name: "Protéine de soja",          aliases: ["proteine soja","soja","soy protein"],
    kcal:338, protein:81.0, fat:1.0,  carbs:8.0,  fiber:0.0, salt:1.0, category:"Compléments" },

  // ── BOISSONS (valeurs pour 100 ml ≈ 100 g) ──────────────────────────────
  { name: "Coca Cola (classique)",     aliases: ["coca cola","coca-cola","coca","coke","pepsi","cola"],
    kcal:42,  protein:0.0,  fat:0.0,  carbs:10.6, fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Coca Cola Zero / Light",    aliases: ["coca zero","coca light","coke zero","pepsi zero","cola zero","coca cola zero"],
    kcal:1,   protein:0.0,  fat:0.0,  carbs:0.1,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Fanta Orange",              aliases: ["fanta","fanta orange"],
    kcal:44,  protein:0.0,  fat:0.0,  carbs:10.9, fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Sprite",                    aliases: ["sprite","7up","7 up"],
    kcal:40,  protein:0.0,  fat:0.0,  carbs:10.0, fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Jus d'orange (100%)",       aliases: ["jus orange","jus d orange","orange juice","jus de fruit"],
    kcal:45,  protein:0.7,  fat:0.2,  carbs:10.4, fiber:0.2, salt:0.0, category:"Boissons" },
  { name: "Jus de pomme (100%)",       aliases: ["jus pomme","jus de pomme","apple juice"],
    kcal:46,  protein:0.1,  fat:0.1,  carbs:11.4, fiber:0.1, salt:0.0, category:"Boissons" },
  { name: "Red Bull (classique)",      aliases: ["red bull","redbull","energy drink","monster"],
    kcal:45,  protein:0.0,  fat:0.0,  carbs:11.0, fiber:0.0, salt:0.1, category:"Boissons" },
  { name: "Bière (5°)",                aliases: ["biere","bière","beer","cerveza"],
    kcal:43,  protein:0.5,  fat:0.0,  carbs:3.6,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Café (expresso)",           aliases: ["cafe","café","coffee","expresso","espresso"],
    kcal:2,   protein:0.1,  fat:0.0,  carbs:0.0,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Lait chocolaté",            aliases: ["lait chocolat","lait chocolaté","nesquik","ovomaltine"],
    kcal:72,  protein:3.5,  fat:2.5,  carbs:9.8,  fiber:0.1, salt:0.1, category:"Boissons" },

  // ── CHOCOLAT & CONFISERIES ───────────────────────────────────────────────
  { name: "Chocolat au lait",          aliases: ["chocolat lait","chocolat au lait","milk chocolate","milka","kinder"],
    kcal:535, protein:7.7,  fat:29.7, carbs:59.5, fiber:1.5, salt:0.2, category:"Sucreries" },
  { name: "Chocolat noir (70%)",       aliases: ["chocolat noir","dark chocolate","chocolat 70","cacao"],
    kcal:598, protein:7.8,  fat:42.6, carbs:45.9, fiber:10.9,salt:0.0, category:"Sucreries" },
  { name: "Chocolat blanc",            aliases: ["chocolat blanc","white chocolate"],
    kcal:539, protein:5.9,  fat:32.1, carbs:58.3, fiber:0.0, salt:0.2, category:"Sucreries" },
  { name: "Barre Mars",                aliases: ["mars","barre mars","mars bar"],
    kcal:449, protein:4.2,  fat:17.4, carbs:68.5, fiber:0.6, salt:0.3, category:"Sucreries" },
  { name: "Barre Snickers",            aliases: ["snickers","snicker","barre snickers"],
    kcal:488, protein:8.8,  fat:23.6, carbs:62.3, fiber:1.5, salt:0.3, category:"Sucreries" },
  { name: "Barre KitKat",              aliases: ["kitkat","kit kat","barre kitkat"],
    kcal:518, protein:6.7,  fat:27.2, carbs:63.7, fiber:1.1, salt:0.2, category:"Sucreries" },
  { name: "Barre Twix",                aliases: ["twix","barre twix"],
    kcal:495, protein:4.5,  fat:23.7, carbs:65.6, fiber:0.8, salt:0.3, category:"Sucreries" },
  { name: "Barre Bounty",              aliases: ["bounty","barre bounty"],
    kcal:471, protein:3.7,  fat:23.7, carbs:60.9, fiber:2.8, salt:0.2, category:"Sucreries" },
  { name: "Nutella",                   aliases: ["nutella","pate a tartiner","pate noisette"],
    kcal:530, protein:6.3,  fat:30.9, carbs:57.5, fiber:2.0, salt:0.1, category:"Sucreries" },
  { name: "Bonbons gélifiés (Haribo)", aliases: ["haribo","bonbon","bonbons","gummies","oursons","tagada"],
    kcal:325, protein:8.0,  fat:0.5,  carbs:74.0, fiber:0.0, salt:0.1, category:"Sucreries" },
  { name: "Chewing gum",               aliases: ["chewing gum","chewing-gum","gomme","mâchoire"],
    kcal:200, protein:0.0,  fat:0.0,  carbs:70.0, fiber:0.0, salt:0.0, category:"Sucreries" },
  { name: "Caramels",                  aliases: ["caramel","caramels","werther"],
    kcal:380, protein:3.0,  fat:9.0,  carbs:71.0, fiber:0.0, salt:0.4, category:"Sucreries" },
  { name: "Chips (nature)",            aliases: ["chips","crisps","pringles","lays"],
    kcal:536, protein:6.5,  fat:34.6, carbs:51.1, fiber:3.4, salt:1.1, category:"Snacks" },
  { name: "Oreo",                      aliases: ["oreo","oreos"],
    kcal:480, protein:5.4,  fat:20.1, carbs:71.9, fiber:2.2, salt:0.6, category:"Sucreries" },
  { name: "Biscuit LU Petit Beurre",   aliases: ["petit beurre","biscuit lu","lu","biscuit beurre"],
    kcal:440, protein:7.5,  fat:14.8, carbs:69.8, fiber:2.3, salt:0.5, category:"Sucreries" },
  { name: "Croissant",                 aliases: ["croissant"],
    kcal:406, protein:8.2,  fat:21.0, carbs:47.3, fiber:2.1, salt:0.9, category:"Boulangerie" },
  { name: "Pain au chocolat",          aliases: ["pain au chocolat","chocolatine"],
    kcal:394, protein:7.5,  fat:18.9, carbs:49.5, fiber:2.4, salt:0.6, category:"Boulangerie" },

  // ── FAST-FOOD & PLATS PRÉPARÉS ───────────────────────────────────────────
  { name: "Pizza Margherita",          aliases: ["pizza","pizza margherita"],
    kcal:250, protein:11.0, fat:9.0,  carbs:32.0, fiber:2.5, salt:1.5, category:"Plats préparés" },
  { name: "Burger (hamburger)",        aliases: ["burger","hamburger","cheeseburger","bigmac","big mac"],
    kcal:295, protein:15.0, fat:14.0, carbs:28.0, fiber:1.5, salt:1.2, category:"Plats préparés" },
  { name: "Frites",                    aliases: ["frites","french fries","frite"],
    kcal:312, protein:3.4,  fat:15.0, carbs:41.0, fiber:3.8, salt:0.7, category:"Plats préparés" },
  { name: "Nuggets de poulet",         aliases: ["nuggets","chicken nuggets","nugget"],
    kcal:297, protein:14.8, fat:17.9, carbs:20.8, fiber:0.8, salt:1.0, category:"Plats préparés" },
  { name: "Soupe de légumes",          aliases: ["soupe","soup","soupe legumes","soupe legume"],
    kcal:50,  protein:2.5,  fat:1.5,  carbs:7.5,  fiber:2.0, salt:0.8, category:"Plats préparés" },

  // ── VIANDES SUPPLÉMENTAIRES ──────────────────────────────────────────────
  { name: "Veau (côtelette, cuit)",    aliases: ["veau","escalope veau","cote veau","côtelette veau"],
    kcal:172, protein:28.5, fat:5.6,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Lapin (cuit)",              aliases: ["lapin","rabbit"],
    kcal:197, protein:29.1, fat:8.0,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Canard (filet, cuit)",      aliases: ["canard","duck","magret","magret canard"],
    kcal:201, protein:27.7, fat:9.7,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Foie de boeuf (cuit)",      aliases: ["foie boeuf","foie de boeuf","liver"],
    kcal:175, protein:27.0, fat:4.9,  carbs:5.3,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Foie de volaille (cuit)",   aliases: ["foie volaille","foie poulet","chicken liver"],
    kcal:167, protein:24.5, fat:6.5,  carbs:0.9,  fiber:0.0, salt:0.1, category:"Viandes & Poissons" },
  { name: "Jambon blanc (cuit)",       aliases: ["jambon","jambon blanc","jambon cuit","ham"],
    kcal:109, protein:18.4, fat:3.0,  carbs:1.5,  fiber:0.0, salt:1.5, category:"Viandes & Poissons" },
  { name: "Jambon cru (serrano)",      aliases: ["jambon cru","serrano","prosciutto","jambon sec","parma"],
    kcal:145, protein:28.2, fat:3.4,  carbs:0.3,  fiber:0.0, salt:4.5, category:"Viandes & Poissons" },
  { name: "Lardons fumés",             aliases: ["lardons","lardon","bacon","lardons fumés"],
    kcal:334, protein:18.0, fat:28.0, carbs:1.0,  fiber:0.0, salt:2.5, category:"Viandes & Poissons" },
  { name: "Saucisse de Francfort",     aliases: ["saucisse","saucisse francfort","hot dog saucisse","frankfurt","wiener"],
    kcal:290, protein:12.0, fat:26.0, carbs:3.0,  fiber:0.0, salt:1.8, category:"Viandes & Poissons" },
  { name: "Merguez (cuite)",           aliases: ["merguez","merguez cuite"],
    kcal:310, protein:15.0, fat:27.0, carbs:1.5,  fiber:0.0, salt:1.8, category:"Viandes & Poissons" },
  { name: "Chorizo",                   aliases: ["chorizo"],
    kcal:455, protein:24.1, fat:38.3, carbs:2.0,  fiber:0.0, salt:3.6, category:"Viandes & Poissons" },
  { name: "Rôti de boeuf (cuit)",      aliases: ["roti boeuf","rôti de boeuf","roast beef","roti"],
    kcal:185, protein:28.0, fat:7.5,  carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },
  { name: "Saucisson sec",             aliases: ["saucisson","salami","saucisson sec"],
    kcal:430, protein:24.0, fat:36.0, carbs:2.0,  fiber:0.0, salt:3.5, category:"Viandes & Poissons" },
  { name: "Boudin noir",               aliases: ["boudin noir","blood sausage"],
    kcal:275, protein:14.0, fat:21.0, carbs:7.0,  fiber:0.0, salt:1.2, category:"Viandes & Poissons" },

  // ── POISSONS SUPPLÉMENTAIRES ─────────────────────────────────────────────
  { name: "Saumon fumé",               aliases: ["saumon fume","saumon fumé","smoked salmon"],
    kcal:117, protein:18.3, fat:4.3,  carbs:0.0,  fiber:0.0, salt:2.9, category:"Viandes & Poissons" },
  { name: "Dorade (cuite)",            aliases: ["dorade","daurade","sea bream"],
    kcal:128, protein:22.7, fat:3.7,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Bar / Loup (cuit)",         aliases: ["bar","loup","sea bass","loup de mer"],
    kcal:124, protein:23.0, fat:3.2,  carbs:0.0,  fiber:0.0, salt:0.2, category:"Viandes & Poissons" },
  { name: "Sole (cuite)",              aliases: ["sole","sole cuite"],
    kcal:92,  protein:18.7, fat:1.5,  carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },
  { name: "Lieu noir (cuit)",          aliases: ["lieu noir","pollock","colin noir"],
    kcal:92,  protein:19.5, fat:0.9,  carbs:0.0,  fiber:0.0, salt:0.3, category:"Viandes & Poissons" },
  { name: "Truite (cuite)",            aliases: ["truite","trout"],
    kcal:148, protein:20.8, fat:6.6,  carbs:0.0,  fiber:0.0, salt:0.1, category:"Viandes & Poissons" },
  { name: "Hareng fumé",               aliases: ["hareng","hareng fumé","kipper"],
    kcal:217, protein:24.6, fat:12.9, carbs:0.0,  fiber:0.0, salt:0.9, category:"Viandes & Poissons" },
  { name: "Anchois (en boîte)",        aliases: ["anchois","anchovy","anchoix"],
    kcal:210, protein:28.9, fat:9.7,  carbs:0.0,  fiber:0.0, salt:8.3, category:"Viandes & Poissons" },
  { name: "Moules (cuites)",           aliases: ["moules","moule","mussels"],
    kcal:86,  protein:11.9, fat:2.2,  carbs:3.7,  fiber:0.0, salt:0.9, category:"Viandes & Poissons" },
  { name: "Huîtres",                   aliases: ["huitres","huîtres","huitre","oysters"],
    kcal:69,  protein:7.1,  fat:1.7,  carbs:5.1,  fiber:0.0, salt:0.5, category:"Viandes & Poissons" },
  { name: "Calamars (cuits)",          aliases: ["calamars","calmar","squid","calamar"],
    kcal:92,  protein:15.6, fat:1.4,  carbs:3.1,  fiber:0.0, salt:0.5, category:"Viandes & Poissons" },
  { name: "Crabe (cuit)",              aliases: ["crabe","crab"],
    kcal:97,  protein:19.4, fat:1.8,  carbs:0.0,  fiber:0.0, salt:1.0, category:"Viandes & Poissons" },
  { name: "Poulpe (cuit)",             aliases: ["poulpe","octopus"],
    kcal:82,  protein:14.9, fat:1.0,  carbs:2.2,  fiber:0.0, salt:0.6, category:"Viandes & Poissons" },

  // ── FROMAGES SUPPLÉMENTAIRES ─────────────────────────────────────────────
  { name: "Parmesan",                  aliases: ["parmesan","parmigiano","reggiano","parmigiano reggiano"],
    kcal:431, protein:38.5, fat:28.1, carbs:3.2,  fiber:0.0, salt:1.6, category:"Oeufs & Produits laitiers" },
  { name: "Camembert",                 aliases: ["camembert"],
    kcal:299, protein:19.8, fat:24.0, carbs:0.5,  fiber:0.0, salt:1.3, category:"Oeufs & Produits laitiers" },
  { name: "Brie",                      aliases: ["brie"],
    kcal:334, protein:20.8, fat:27.7, carbs:0.5,  fiber:0.0, salt:1.0, category:"Oeufs & Produits laitiers" },
  { name: "Roquefort",                 aliases: ["roquefort","fromage bleu","bleu"],
    kcal:369, protein:21.5, fat:30.6, carbs:2.0,  fiber:0.0, salt:2.6, category:"Oeufs & Produits laitiers" },
  { name: "Comté",                     aliases: ["comte","comté"],
    kcal:413, protein:29.2, fat:32.1, carbs:0.4,  fiber:0.0, salt:1.5, category:"Oeufs & Produits laitiers" },
  { name: "Cheddar",                   aliases: ["cheddar"],
    kcal:403, protein:24.9, fat:33.1, carbs:1.3,  fiber:0.0, salt:1.7, category:"Oeufs & Produits laitiers" },
  { name: "Feta",                      aliases: ["feta"],
    kcal:264, protein:14.2, fat:21.3, carbs:4.1,  fiber:0.0, salt:2.1, category:"Oeufs & Produits laitiers" },
  { name: "Ricotta",                   aliases: ["ricotta"],
    kcal:174, protein:11.3, fat:13.0, carbs:3.0,  fiber:0.0, salt:0.3, category:"Oeufs & Produits laitiers" },
  { name: "Mascarpone",                aliases: ["mascarpone"],
    kcal:429, protein:4.7,  fat:44.0, carbs:2.6,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Yaourt grec (nature)",      aliases: ["yaourt grec","yogurt grec","greek yogurt"],
    kcal:97,  protein:9.0,  fat:5.0,  carbs:3.6,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Petit suisse",              aliases: ["petit suisse","petits suisses"],
    kcal:110, protein:8.0,  fat:7.0,  carbs:4.0,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Lait de soja",              aliases: ["lait soja","lait de soja","soy milk"],
    kcal:43,  protein:3.3,  fat:1.8,  carbs:3.9,  fiber:0.4, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Lait d'amande",             aliases: ["lait amande","lait d amande","almond milk"],
    kcal:24,  protein:0.8,  fat:1.5,  carbs:2.0,  fiber:0.3, salt:0.1, category:"Oeufs & Produits laitiers" },
  { name: "Lait d'avoine",             aliases: ["lait avoine","lait d avoine","oat milk"],
    kcal:47,  protein:1.0,  fat:1.5,  carbs:7.0,  fiber:0.5, salt:0.1, category:"Boissons" },
  { name: "Crème fraîche légère (15%)",aliases: ["creme fraiche legere","crème allégée","creme legere","creme allegee"],
    kcal:162, protein:2.8,  fat:15.0, carbs:3.6,  fiber:0.0, salt:0.1, category:"Oeufs & Produits laitiers" },

  // ── FÉCULENTS SUPPLÉMENTAIRES ────────────────────────────────────────────
  { name: "Couscous (cru)",            aliases: ["couscous cru","semoule couscous"],
    kcal:376, protein:13.0, fat:0.6,  carbs:77.4, fiber:4.4, salt:0.0, category:"Féculents & Céréales" },
  { name: "Couscous (cuit)",           aliases: ["couscous","couscous cuit","semoule cuite"],
    kcal:112, protein:3.8,  fat:0.2,  carbs:23.2, fiber:1.4, salt:0.0, category:"Féculents & Céréales" },
  { name: "Boulgour (cuit)",           aliases: ["boulgour","bulgur","blé bulgur"],
    kcal:83,  protein:3.1,  fat:0.2,  carbs:18.6, fiber:4.5, salt:0.0, category:"Féculents & Céréales" },
  { name: "Semoule de blé (crue)",     aliases: ["semoule","semoule de ble","semolina"],
    kcal:360, protein:12.7, fat:1.1,  carbs:73.8, fiber:3.9, salt:0.0, category:"Féculents & Céréales" },
  { name: "Riz basmati (cru)",         aliases: ["riz basmati","basmati"],
    kcal:357, protein:7.5,  fat:0.5,  carbs:79.0, fiber:0.4, salt:0.0, category:"Féculents & Céréales" },
  { name: "Riz complet (cuit)",        aliases: ["riz complet","brown rice","riz brun"],
    kcal:111, protein:2.6,  fat:0.9,  carbs:23.0, fiber:1.8, salt:0.0, category:"Féculents & Céréales" },
  { name: "Pain de seigle",            aliases: ["pain seigle","pain de seigle","rye bread"],
    kcal:259, protein:8.5,  fat:3.3,  carbs:48.3, fiber:6.2, salt:1.0, category:"Féculents & Céréales" },
  { name: "Pain pita",                 aliases: ["pita","pain pita","pita bread"],
    kcal:275, protein:9.1,  fat:1.2,  carbs:55.7, fiber:2.2, salt:0.8, category:"Féculents & Céréales" },
  { name: "Naan",                      aliases: ["naan","pain naan","galette naan"],
    kcal:317, protein:9.8,  fat:5.1,  carbs:56.1, fiber:2.3, salt:0.9, category:"Féculents & Céréales" },
  { name: "Tortilla de blé (wrap)",    aliases: ["tortilla","wrap","wraps","galette blé","fajita"],
    kcal:297, protein:8.0,  fat:6.5,  carbs:51.9, fiber:2.0, salt:1.0, category:"Féculents & Céréales" },
  { name: "Maïs (épi cuit)",           aliases: ["mais","maïs","corn","épi maïs","maïs cuit"],
    kcal:96,  protein:3.4,  fat:1.5,  carbs:19.0, fiber:2.7, salt:0.0, category:"Féculents & Céréales" },
  { name: "Maïs (en boîte)",           aliases: ["mais boite","maïs boite","maïs conserve","sweet corn"],
    kcal:85,  protein:3.2,  fat:1.2,  carbs:17.1, fiber:2.0, salt:0.3, category:"Féculents & Céréales" },
  { name: "Corn Flakes",               aliases: ["corn flakes","cornflakes","cereales corn flakes","kellog"],
    kcal:372, protein:7.5,  fat:0.4,  carbs:84.0, fiber:3.0, salt:1.1, category:"Féculents & Céréales" },
  { name: "Granola (nature)",          aliases: ["granola","muesli granola"],
    kcal:471, protein:10.0, fat:19.9, carbs:64.0, fiber:5.3, salt:0.2, category:"Féculents & Céréales" },
  { name: "Polenta (cuite)",           aliases: ["polenta","polenta cuite","semoule maïs cuite"],
    kcal:70,  protein:1.7,  fat:0.3,  carbs:15.1, fiber:1.0, salt:0.0, category:"Féculents & Céréales" },
  { name: "Gnocchis (cuits)",          aliases: ["gnocchis","gnocchi","gnocci"],
    kcal:131, protein:2.9,  fat:1.2,  carbs:27.2, fiber:1.2, salt:0.4, category:"Féculents & Céréales" },
  { name: "Orge perlé (cuit)",         aliases: ["orge","barley","orge perle","orge perlé"],
    kcal:123, protein:2.3,  fat:0.4,  carbs:28.2, fiber:3.8, salt:0.0, category:"Féculents & Céréales" },
  { name: "Millet (cuit)",             aliases: ["millet","mil"],
    kcal:119, protein:3.5,  fat:1.0,  carbs:23.7, fiber:1.3, salt:0.0, category:"Féculents & Céréales" },

  // ── LÉGUMINEUSES SUPPLÉMENTAIRES ─────────────────────────────────────────
  { name: "Haricots blancs (cuits)",   aliases: ["haricots blancs","haricot blanc","white beans","flageolets"],
    kcal:139, protein:9.7,  fat:0.5,  carbs:25.1, fiber:10.5,salt:0.0, category:"Légumineuses" },
  { name: "Pois cassés (cuits)",       aliases: ["pois casses","pois cassés","split peas"],
    kcal:118, protein:8.3,  fat:0.4,  carbs:21.1, fiber:8.3, salt:0.0, category:"Légumineuses" },
  { name: "Fèves (cuites)",            aliases: ["feves","fèves","feve","fava beans"],
    kcal:110, protein:7.6,  fat:0.4,  carbs:19.7, fiber:5.4, salt:0.0, category:"Légumineuses" },
  { name: "Haricots noirs (cuits)",    aliases: ["haricots noirs","black beans","haricot noir"],
    kcal:132, protein:8.9,  fat:0.5,  carbs:23.7, fiber:8.7, salt:0.0, category:"Légumineuses" },
  { name: "Edamame",                   aliases: ["edamame","soja vert","feve soja"],
    kcal:122, protein:11.9, fat:5.2,  carbs:8.9,  fiber:5.2, salt:0.0, category:"Légumineuses" },
  { name: "Tofu ferme",                aliases: ["tofu","tofu ferme","bean curd"],
    kcal:76,  protein:8.1,  fat:4.2,  carbs:1.9,  fiber:0.3, salt:0.3, category:"Légumineuses" },
  { name: "Tempeh",                    aliases: ["tempeh"],
    kcal:192, protein:19.0, fat:10.8, carbs:9.4,  fiber:0.0, salt:0.0, category:"Légumineuses" },
  { name: "Houmous",                   aliases: ["houmous","hummus","hoummos"],
    kcal:166, protein:7.9,  fat:9.6,  carbs:14.3, fiber:6.0, salt:0.7, category:"Légumineuses" },

  // ── LÉGUMES SUPPLÉMENTAIRES ──────────────────────────────────────────────
  { name: "Oignon",                    aliases: ["oignon","oignons","onion"],
    kcal:40,  protein:1.1,  fat:0.1,  carbs:9.3,  fiber:1.7, salt:0.0, category:"Légumes" },
  { name: "Ail",                       aliases: ["ail","garlic"],
    kcal:149, protein:6.4,  fat:0.5,  carbs:33.1, fiber:2.1, salt:0.0, category:"Légumes" },
  { name: "Poireau (cuit)",            aliases: ["poireau","poireaux","leek"],
    kcal:31,  protein:0.8,  fat:0.2,  carbs:7.6,  fiber:1.8, salt:0.0, category:"Légumes" },
  { name: "Céleri branche",            aliases: ["celeri","céleri","celery"],
    kcal:14,  protein:0.7,  fat:0.2,  carbs:3.0,  fiber:1.6, salt:0.1, category:"Légumes" },
  { name: "Chou blanc (cru)",          aliases: ["chou blanc","chou","cabbage"],
    kcal:25,  protein:1.3,  fat:0.1,  carbs:5.8,  fiber:2.5, salt:0.0, category:"Légumes" },
  { name: "Chou-fleur (cuit)",         aliases: ["chou fleur","chou-fleur","cauliflower"],
    kcal:23,  protein:1.8,  fat:0.3,  carbs:4.5,  fiber:2.1, salt:0.0, category:"Légumes" },
  { name: "Chou de Bruxelles (cuit)",  aliases: ["chou bruxelles","chou de bruxelles","brussels sprouts"],
    kcal:36,  protein:2.6,  fat:0.5,  carbs:7.1,  fiber:3.8, salt:0.0, category:"Légumes" },
  { name: "Aubergine (cuite)",         aliases: ["aubergine","eggplant"],
    kcal:35,  protein:0.8,  fat:0.2,  carbs:8.7,  fiber:2.5, salt:0.0, category:"Légumes" },
  { name: "Betterave rouge (cuite)",   aliases: ["betterave","betterave rouge","beet","beetroot"],
    kcal:44,  protein:1.7,  fat:0.2,  carbs:9.9,  fiber:2.0, salt:0.1, category:"Légumes" },
  { name: "Artichaut (cuit)",          aliases: ["artichaut","artichoke","artichaux"],
    kcal:53,  protein:2.9,  fat:0.3,  carbs:10.5, fiber:5.4, salt:0.1, category:"Légumes" },
  { name: "Asperges (cuites)",         aliases: ["asperge","asperges","asparagus"],
    kcal:22,  protein:2.4,  fat:0.2,  carbs:4.1,  fiber:2.1, salt:0.0, category:"Légumes" },
  { name: "Haricots verts (cuits)",    aliases: ["haricots verts","haricot vert","green beans"],
    kcal:31,  protein:1.8,  fat:0.1,  carbs:7.1,  fiber:3.4, salt:0.0, category:"Légumes" },
  { name: "Petits pois (cuits)",       aliases: ["petits pois","petit pois","peas","pois"],
    kcal:84,  protein:5.4,  fat:0.4,  carbs:15.6, fiber:5.5, salt:0.0, category:"Légumes" },
  { name: "Poivron vert",              aliases: ["poivron vert","green pepper"],
    kcal:20,  protein:0.9,  fat:0.2,  carbs:4.6,  fiber:1.7, salt:0.0, category:"Légumes" },
  { name: "Poivron jaune",             aliases: ["poivron jaune","yellow pepper"],
    kcal:27,  protein:1.0,  fat:0.2,  carbs:6.3,  fiber:0.9, salt:0.0, category:"Légumes" },
  { name: "Radis",                     aliases: ["radis","radish"],
    kcal:16,  protein:0.7,  fat:0.1,  carbs:3.4,  fiber:1.6, salt:0.0, category:"Légumes" },
  { name: "Navet (cuit)",              aliases: ["navet","turnip"],
    kcal:28,  protein:0.9,  fat:0.1,  carbs:6.4,  fiber:1.8, salt:0.0, category:"Légumes" },
  { name: "Fenouil (cru)",             aliases: ["fenouil","fennel"],
    kcal:31,  protein:1.2,  fat:0.2,  carbs:7.3,  fiber:3.1, salt:0.1, category:"Légumes" },
  { name: "Roquette",                  aliases: ["roquette","rocket","rucola"],
    kcal:25,  protein:2.6,  fat:0.7,  carbs:3.7,  fiber:1.6, salt:0.1, category:"Légumes" },
  { name: "Laitue / Salade verte",     aliases: ["laitue","salade","salade verte","lettuce","iceberg"],
    kcal:14,  protein:1.4,  fat:0.2,  carbs:2.2,  fiber:1.3, salt:0.0, category:"Légumes" },
  { name: "Endive",                    aliases: ["endive","chicorée","endives"],
    kcal:17,  protein:0.9,  fat:0.1,  carbs:3.6,  fiber:3.1, salt:0.0, category:"Légumes" },
  { name: "Potiron / Potimarron",      aliases: ["potiron","potimarron","courge","butternut","squash"],
    kcal:26,  protein:1.0,  fat:0.1,  carbs:6.5,  fiber:0.5, salt:0.0, category:"Légumes" },
  { name: "Avocat (fruit)",            aliases: ["avocat fruit"],
    kcal:160, protein:2.0,  fat:14.7, carbs:8.5,  fiber:6.7, salt:0.0, category:"Légumes" },
  { name: "Maïs doux (cru)",           aliases: ["mais doux","maïs doux","corn raw"],
    kcal:86,  protein:3.3,  fat:1.4,  carbs:18.7, fiber:2.0, salt:0.0, category:"Légumes" },

  // ── FRUITS SUPPLÉMENTAIRES ───────────────────────────────────────────────
  { name: "Raisin blanc",              aliases: ["raisin blanc","raisin","grape"],
    kcal:69,  protein:0.7,  fat:0.2,  carbs:18.1, fiber:0.9, salt:0.0, category:"Fruits" },
  { name: "Raisin rouge / noir",       aliases: ["raisin rouge","raisin noir","red grape"],
    kcal:71,  protein:0.7,  fat:0.2,  carbs:18.0, fiber:0.9, salt:0.0, category:"Fruits" },
  { name: "Poire",                     aliases: ["poire","pear"],
    kcal:57,  protein:0.4,  fat:0.1,  carbs:15.2, fiber:3.1, salt:0.0, category:"Fruits" },
  { name: "Pêche",                     aliases: ["peche","pêche","peach"],
    kcal:39,  protein:0.9,  fat:0.3,  carbs:9.5,  fiber:1.5, salt:0.0, category:"Fruits" },
  { name: "Nectarine",                 aliases: ["nectarine","brugnon"],
    kcal:44,  protein:1.1,  fat:0.3,  carbs:10.6, fiber:1.7, salt:0.0, category:"Fruits" },
  { name: "Abricot",                   aliases: ["abricot","abricots","apricot"],
    kcal:48,  protein:1.4,  fat:0.4,  carbs:11.1, fiber:2.0, salt:0.0, category:"Fruits" },
  { name: "Cerise",                    aliases: ["cerise","cerises","cherry","cherries"],
    kcal:63,  protein:1.1,  fat:0.2,  carbs:16.0, fiber:2.1, salt:0.0, category:"Fruits" },
  { name: "Kiwi",                      aliases: ["kiwi"],
    kcal:61,  protein:1.1,  fat:0.5,  carbs:14.7, fiber:3.0, salt:0.0, category:"Fruits" },
  { name: "Ananas",                    aliases: ["ananas","pineapple"],
    kcal:50,  protein:0.5,  fat:0.1,  carbs:13.1, fiber:1.4, salt:0.0, category:"Fruits" },
  { name: "Mangue",                    aliases: ["mangue","mango"],
    kcal:60,  protein:0.8,  fat:0.4,  carbs:14.9, fiber:1.6, salt:0.0, category:"Fruits" },
  { name: "Papaye",                    aliases: ["papaye","papaya"],
    kcal:43,  protein:0.5,  fat:0.3,  carbs:10.8, fiber:1.7, salt:0.0, category:"Fruits" },
  { name: "Pastèque",                  aliases: ["pasteque","pastèque","watermelon"],
    kcal:30,  protein:0.6,  fat:0.2,  carbs:7.6,  fiber:0.4, salt:0.0, category:"Fruits" },
  { name: "Melon (cantaloup)",         aliases: ["melon","cantaloup","cantaloupe"],
    kcal:34,  protein:0.8,  fat:0.2,  carbs:8.2,  fiber:0.9, salt:0.0, category:"Fruits" },
  { name: "Litchi",                    aliases: ["litchi","lychee","lichi"],
    kcal:66,  protein:0.8,  fat:0.4,  carbs:16.5, fiber:1.3, salt:0.0, category:"Fruits" },
  { name: "Grenade",                   aliases: ["grenade","pomegranate"],
    kcal:83,  protein:1.7,  fat:1.2,  carbs:18.7, fiber:4.0, salt:0.0, category:"Fruits" },
  { name: "Figue fraîche",             aliases: ["figue","figues","fig"],
    kcal:74,  protein:0.8,  fat:0.3,  carbs:19.2, fiber:2.9, salt:0.0, category:"Fruits" },
  { name: "Figue sèche",               aliases: ["figue seche","figue sèche","dried fig"],
    kcal:249, protein:3.3,  fat:0.9,  carbs:63.9, fiber:9.8, salt:0.0, category:"Fruits" },
  { name: "Datte",                     aliases: ["datte","dattes","date","dates"],
    kcal:282, protein:2.5,  fat:0.4,  carbs:75.0, fiber:8.0, salt:0.0, category:"Fruits" },
  { name: "Pruneaux (séchés)",         aliases: ["pruneaux","pruneau","prunes","prune"],
    kcal:240, protein:2.2,  fat:0.4,  carbs:63.9, fiber:7.1, salt:0.0, category:"Fruits" },
  { name: "Raisins secs",              aliases: ["raisins secs","raisin sec","sultana"],
    kcal:299, protein:3.1,  fat:0.5,  carbs:79.2, fiber:3.7, salt:0.0, category:"Fruits" },
  { name: "Noix de coco (pulpe)",      aliases: ["noix de coco","coco","coconut","pulpe coco"],
    kcal:354, protein:3.3,  fat:33.5, carbs:15.2, fiber:9.0, salt:0.0, category:"Fruits" },
  { name: "Citron",                    aliases: ["citron","lemon"],
    kcal:29,  protein:1.1,  fat:0.3,  carbs:9.3,  fiber:2.8, salt:0.0, category:"Fruits" },
  { name: "Pamplemousse",              aliases: ["pamplemousse","grapefruit"],
    kcal:42,  protein:0.8,  fat:0.1,  carbs:10.7, fiber:1.6, salt:0.0, category:"Fruits" },
  { name: "Mandarine",                 aliases: ["mandarine","clementine","clémentine","tangerine"],
    kcal:53,  protein:0.8,  fat:0.3,  carbs:13.3, fiber:1.8, salt:0.0, category:"Fruits" },
  { name: "Fruit de la passion",       aliases: ["fruit de la passion","passion fruit","maracuja"],
    kcal:97,  protein:2.2,  fat:0.7,  carbs:23.4, fiber:10.4,salt:0.0, category:"Fruits" },
  { name: "Framboise",                 aliases: ["framboise","framboises","raspberry"],
    kcal:52,  protein:1.2,  fat:0.7,  carbs:11.9, fiber:6.5, salt:0.0, category:"Fruits" },
  { name: "Mûres",                     aliases: ["mure","mûres","mûre","blackberry"],
    kcal:43,  protein:1.4,  fat:0.5,  carbs:9.6,  fiber:5.3, salt:0.0, category:"Fruits" },
  { name: "Cassis",                    aliases: ["cassis","blackcurrant"],
    kcal:63,  protein:1.4,  fat:0.4,  carbs:15.4, fiber:7.9, salt:0.0, category:"Fruits" },
  { name: "Melon miel (honeydew)",     aliases: ["melon miel","honeydew"],
    kcal:36,  protein:0.5,  fat:0.1,  carbs:9.1,  fiber:0.8, salt:0.0, category:"Fruits" },

  // ── NOIX & GRAINES SUPPLÉMENTAIRES ──────────────────────────────────────
  { name: "Noisettes",                 aliases: ["noisette","noisettes","hazelnut"],
    kcal:628, protein:15.0, fat:60.8, carbs:16.7, fiber:9.7, salt:0.0, category:"Noix & Graines" },
  { name: "Pistaches",                 aliases: ["pistache","pistaches","pistachio"],
    kcal:562, protein:20.2, fat:45.3, carbs:27.2, fiber:10.6,salt:0.0, category:"Noix & Graines" },
  { name: "Cacahuètes (nature)",       aliases: ["cacahuetes","cacahuète","peanuts","arachides"],
    kcal:567, protein:25.8, fat:49.2, carbs:16.1, fiber:8.5, salt:0.0, category:"Noix & Graines" },
  { name: "Graines de tournesol",      aliases: ["tournesol","graines tournesol","sunflower seeds"],
    kcal:584, protein:20.8, fat:51.5, carbs:20.0, fiber:8.6, salt:0.0, category:"Noix & Graines" },
  { name: "Graines de lin",            aliases: ["lin","graines lin","flaxseed","linseed"],
    kcal:534, protein:18.3, fat:42.2, carbs:28.9, fiber:27.3,salt:0.0, category:"Noix & Graines" },
  { name: "Graines de courge",         aliases: ["courge graines","pepitas","graines de courge"],
    kcal:559, protein:30.2, fat:49.1, carbs:10.7, fiber:6.0, salt:0.0, category:"Noix & Graines" },
  { name: "Graines de sésame",         aliases: ["sesame","graines sesame","sesame seeds"],
    kcal:573, protein:17.7, fat:49.7, carbs:23.5, fiber:11.8,salt:0.0, category:"Noix & Graines" },
  { name: "Tahini (purée de sésame)",  aliases: ["tahini","tahine","creme sesame"],
    kcal:595, protein:17.0, fat:53.8, carbs:21.2, fiber:9.3, salt:0.1, category:"Noix & Graines" },
  { name: "Noix de macadamia",         aliases: ["macadamia","noix macadamia"],
    kcal:718, protein:7.9,  fat:75.8, carbs:13.8, fiber:8.6, salt:0.0, category:"Noix & Graines" },
  { name: "Noix du Brésil",            aliases: ["noix bresil","noix du bresil","brazil nut"],
    kcal:656, protein:14.3, fat:66.4, carbs:12.3, fiber:7.5, salt:0.0, category:"Noix & Graines" },
  { name: "Noix de pécan",             aliases: ["pecan","noix de pecan","noix pecan"],
    kcal:691, protein:9.2,  fat:71.9, carbs:13.9, fiber:9.6, salt:0.0, category:"Noix & Graines" },

  // ── MATIÈRES GRASSES SUPPLÉMENTAIRES ────────────────────────────────────
  { name: "Huile de tournesol",        aliases: ["huile tournesol","sunflower oil"],
    kcal:884, protein:0.0,  fat:100.0,carbs:0.0,  fiber:0.0, salt:0.0, category:"Matières grasses" },
  { name: "Huile de colza",            aliases: ["huile colza","rapeseed oil","canola oil"],
    kcal:884, protein:0.0,  fat:100.0,carbs:0.0,  fiber:0.0, salt:0.0, category:"Matières grasses" },
  { name: "Margarine",                 aliases: ["margarine","matiere grasse vegetale"],
    kcal:717, protein:0.2,  fat:80.0, carbs:0.7,  fiber:0.0, salt:1.1, category:"Matières grasses" },
  { name: "Huile d'arachide",          aliases: ["huile arachide","huile cacahuete","peanut oil"],
    kcal:884, protein:0.0,  fat:100.0,carbs:0.0,  fiber:0.0, salt:0.0, category:"Matières grasses" },

  // ── COMPLÉMENTS SUPPLÉMENTAIRES ──────────────────────────────────────────
  { name: "Caséine (protéine lente)",  aliases: ["caseine","caséine","micellar casein"],
    kcal:370, protein:80.0, fat:2.0,  carbs:6.0,  fiber:0.0, salt:0.4, category:"Compléments" },
  { name: "Protéine de pois",          aliases: ["proteine pois","pea protein"],
    kcal:360, protein:80.0, fat:2.5,  carbs:5.0,  fiber:1.0, salt:1.2, category:"Compléments" },

  // ── BOISSONS SUPPLÉMENTAIRES ─────────────────────────────────────────────
  { name: "Eau plate",                 aliases: ["eau","water","eau plate"],
    kcal:0,   protein:0.0,  fat:0.0,  carbs:0.0,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Thé vert (infusion)",       aliases: ["the vert","thé vert","green tea"],
    kcal:1,   protein:0.0,  fat:0.0,  carbs:0.2,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Thé noir (infusion)",       aliases: ["the noir","thé noir","black tea","the"],
    kcal:1,   protein:0.1,  fat:0.0,  carbs:0.2,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Café au lait",              aliases: ["cafe au lait","café au lait","latte"],
    kcal:38,  protein:2.1,  fat:1.8,  carbs:3.8,  fiber:0.0, salt:0.1, category:"Boissons" },
  { name: "Cappuccino",                aliases: ["cappuccino","capuccino"],
    kcal:40,  protein:2.5,  fat:1.9,  carbs:4.0,  fiber:0.0, salt:0.1, category:"Boissons" },
  { name: "Jus de raisin (100%)",      aliases: ["jus raisin","jus de raisin","grape juice"],
    kcal:60,  protein:0.4,  fat:0.1,  carbs:14.8, fiber:0.2, salt:0.0, category:"Boissons" },
  { name: "Jus de carotte",            aliases: ["jus carotte","jus de carotte","carrot juice"],
    kcal:40,  protein:0.9,  fat:0.2,  carbs:9.3,  fiber:0.0, salt:0.1, category:"Boissons" },
  { name: "Jus de tomate",             aliases: ["jus tomate","jus de tomate","tomato juice"],
    kcal:17,  protein:0.8,  fat:0.1,  carbs:4.2,  fiber:0.4, salt:0.4, category:"Boissons" },
  { name: "Vin rouge",                 aliases: ["vin rouge","red wine"],
    kcal:85,  protein:0.1,  fat:0.0,  carbs:2.6,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Vin blanc (sec)",           aliases: ["vin blanc","white wine"],
    kcal:82,  protein:0.1,  fat:0.0,  carbs:2.6,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Champagne",                 aliases: ["champagne","prosecco","cava","mousseux"],
    kcal:76,  protein:0.3,  fat:0.0,  carbs:1.4,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Whisky / Bourbon",          aliases: ["whisky","whiskey","bourbon"],
    kcal:250, protein:0.0,  fat:0.0,  carbs:0.1,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Vodka",                     aliases: ["vodka"],
    kcal:231, protein:0.0,  fat:0.0,  carbs:0.0,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Rhum",                      aliases: ["rhum","rum"],
    kcal:231, protein:0.0,  fat:0.0,  carbs:0.0,  fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Limonade",                  aliases: ["limonade","lemonade","citron pressé"],
    kcal:40,  protein:0.0,  fat:0.0,  carbs:10.0, fiber:0.0, salt:0.0, category:"Boissons" },
  { name: "Kombucha",                  aliases: ["kombucha"],
    kcal:16,  protein:0.0,  fat:0.0,  carbs:4.0,  fiber:0.0, salt:0.0, category:"Boissons" },

  // ── CONDIMENTS & SAUCES ──────────────────────────────────────────────────
  { name: "Miel",                      aliases: ["miel","honey"],
    kcal:304, protein:0.3,  fat:0.0,  carbs:82.4, fiber:0.2, salt:0.0, category:"Sucreries" },
  { name: "Confiture (standard)",      aliases: ["confiture","jam","marmelade"],
    kcal:250, protein:0.5,  fat:0.1,  carbs:65.0, fiber:1.0, salt:0.0, category:"Sucreries" },
  { name: "Sucre blanc",               aliases: ["sucre","sucre blanc","sugar"],
    kcal:387, protein:0.0,  fat:0.0,  carbs:99.8, fiber:0.0, salt:0.0, category:"Sucreries" },
  { name: "Sucre brun / Cassonade",    aliases: ["sucre brun","cassonade","brown sugar"],
    kcal:380, protein:0.1,  fat:0.0,  carbs:98.1, fiber:0.0, salt:0.0, category:"Sucreries" },
  { name: "Ketchup",                   aliases: ["ketchup","catsup"],
    kcal:100, protein:1.0,  fat:0.1,  carbs:25.0, fiber:0.5, salt:1.7, category:"Plats préparés" },
  { name: "Mayonnaise",                aliases: ["mayonnaise","mayo"],
    kcal:680, protein:1.0,  fat:75.0, carbs:2.5,  fiber:0.0, salt:1.2, category:"Matières grasses" },
  { name: "Moutarde",                  aliases: ["moutarde","mustard"],
    kcal:66,  protein:4.4,  fat:3.3,  carbs:6.4,  fiber:3.3, salt:2.3, category:"Plats préparés" },
  { name: "Sauce soja",                aliases: ["sauce soja","soja sauce","soy sauce"],
    kcal:53,  protein:8.1,  fat:0.1,  carbs:4.9,  fiber:0.8, salt:5.7, category:"Plats préparés" },
  { name: "Vinaigre balsamique",       aliases: ["vinaigre balsamique","balsamique","balsamic"],
    kcal:88,  protein:0.5,  fat:0.0,  carbs:17.0, fiber:0.0, salt:0.2, category:"Plats préparés" },
  { name: "Crème de coco",             aliases: ["creme coco","crème de coco","coconut cream"],
    kcal:330, protein:3.3,  fat:34.0, carbs:6.7,  fiber:2.0, salt:0.0, category:"Matières grasses" },

  // ── BOULANGERIE / PÂTISSERIE SUPPLÉMENTAIRES ────────────────────────────
  { name: "Madeleine",                 aliases: ["madeleine","madeleines"],
    kcal:408, protein:7.0,  fat:14.6, carbs:63.2, fiber:1.5, salt:0.7, category:"Boulangerie" },
  { name: "Brioche",                   aliases: ["brioche"],
    kcal:357, protein:9.0,  fat:14.0, carbs:50.0, fiber:1.5, salt:0.7, category:"Boulangerie" },
  { name: "Cake au citron",            aliases: ["cake citron","cake"],
    kcal:380, protein:5.5,  fat:17.5, carbs:52.0, fiber:0.8, salt:0.5, category:"Boulangerie" },
  { name: "Crêpe nature",              aliases: ["crepe","crêpe","crepes","crêpes"],
    kcal:189, protein:5.0,  fat:7.0,  carbs:27.0, fiber:0.9, salt:0.4, category:"Boulangerie" },
  { name: "Gaufre",                    aliases: ["gaufre","gaufres","waffle"],
    kcal:291, protein:6.0,  fat:12.0, carbs:40.0, fiber:1.0, salt:0.6, category:"Boulangerie" },
  { name: "Donut (glaçage)",           aliases: ["donut","doughnut","beignet"],
    kcal:452, protein:5.4,  fat:25.0, carbs:51.5, fiber:1.4, salt:0.6, category:"Boulangerie" },
  { name: "Muffin (myrtilles)",        aliases: ["muffin","muffins"],
    kcal:377, protein:5.5,  fat:14.2, carbs:57.8, fiber:1.2, salt:0.6, category:"Boulangerie" },
  { name: "Macaron (ganache)",         aliases: ["macaron","macarons","macaron français"],
    kcal:400, protein:6.0,  fat:13.0, carbs:65.0, fiber:0.8, salt:0.1, category:"Boulangerie" },
  { name: "Éclair au chocolat",        aliases: ["eclair","éclair","éclair chocolat"],
    kcal:277, protein:6.5,  fat:12.5, carbs:36.0, fiber:0.8, salt:0.4, category:"Boulangerie" },
  { name: "Tarte aux pommes",          aliases: ["tarte pommes","tarte aux pommes","apple pie"],
    kcal:237, protein:2.4,  fat:10.0, carbs:34.5, fiber:1.5, salt:0.3, category:"Boulangerie" },
  { name: "Pancake",                   aliases: ["pancake","pancakes"],
    kcal:277, protein:7.0,  fat:9.5,  carbs:42.5, fiber:1.0, salt:0.5, category:"Boulangerie" },
  { name: "Pain au lait",              aliases: ["pain au lait","petit pain lait"],
    kcal:330, protein:9.0,  fat:8.5,  carbs:54.0, fiber:2.0, salt:0.7, category:"Boulangerie" },

  // ── PLATS PRÉPARÉS SUPPLÉMENTAIRES ──────────────────────────────────────
  { name: "Kebab (viande + pain)",     aliases: ["kebab","doner kebab","gyros"],
    kcal:260, protein:15.0, fat:10.5, carbs:27.0, fiber:1.5, salt:1.3, category:"Plats préparés" },
  { name: "Hot dog",                   aliases: ["hot dog","hotdog"],
    kcal:290, protein:11.0, fat:17.0, carbs:24.0, fiber:1.0, salt:1.5, category:"Plats préparés" },
  { name: "Sandwich jambon-beurre",    aliases: ["sandwich jambon","jambon beurre","sandwich"],
    kcal:235, protein:10.5, fat:8.5,  carbs:30.0, fiber:1.5, salt:1.3, category:"Plats préparés" },
  { name: "Croque-monsieur",           aliases: ["croque monsieur","croque-monsieur","croque"],
    kcal:292, protein:14.5, fat:14.5, carbs:27.0, fiber:1.5, salt:1.4, category:"Plats préparés" },
  { name: "Quiche lorraine",           aliases: ["quiche","quiche lorraine"],
    kcal:290, protein:9.5,  fat:20.5, carbs:19.0, fiber:0.8, salt:1.1, category:"Plats préparés" },
  { name: "Lasagnes (cuites)",         aliases: ["lasagnes","lasagne","lasagna"],
    kcal:166, protein:9.5,  fat:7.0,  carbs:17.0, fiber:1.5, salt:0.8, category:"Plats préparés" },
  { name: "Hachis parmentier",         aliases: ["hachis parmentier","parmentier"],
    kcal:132, protein:7.5,  fat:6.5,  carbs:12.0, fiber:1.2, salt:0.7, category:"Plats préparés" },
  { name: "Gratin dauphinois",         aliases: ["gratin dauphinois","gratin pommes de terre","gratin"],
    kcal:175, protein:3.8,  fat:10.5, carbs:17.5, fiber:1.5, salt:0.6, category:"Plats préparés" },
  { name: "Taboulé",                   aliases: ["taboule","taboulé","tabbouleh"],
    kcal:142, protein:3.5,  fat:5.5,  carbs:21.0, fiber:2.5, salt:0.5, category:"Plats préparés" },
  { name: "Omelette nature",           aliases: ["omelette","omelette nature"],
    kcal:154, protein:11.0, fat:12.0, carbs:0.5,  fiber:0.0, salt:0.5, category:"Plats préparés" },
  { name: "Riz cantonais",             aliases: ["riz cantonnais","riz cantonais","fried rice"],
    kcal:163, protein:5.5,  fat:5.5,  carbs:24.0, fiber:1.0, salt:0.8, category:"Plats préparés" },
  { name: "Sushi (maki)",              aliases: ["maki","sushi maki","makis"],
    kcal:143, protein:5.7,  fat:1.5,  carbs:28.5, fiber:0.8, salt:0.6, category:"Plats préparés" },
  { name: "Sushi (nigiri)",            aliases: ["nigiri","sushi nigiri"],
    kcal:170, protein:8.5,  fat:1.5,  carbs:31.0, fiber:0.3, salt:0.7, category:"Plats préparés" },
  { name: "Wrap poulet-crudités",      aliases: ["wrap poulet","wrap chicken"],
    kcal:210, protein:15.0, fat:7.5,  carbs:23.0, fiber:2.0, salt:1.0, category:"Plats préparés" },
  { name: "Salade César",              aliases: ["salade cesar","caesar salad","salade caesar"],
    kcal:150, protein:8.0,  fat:10.5, carbs:8.0,  fiber:1.5, salt:0.7, category:"Plats préparés" },
  { name: "Fallafel (frit)",           aliases: ["fallafel","falafel"],
    kcal:333, protein:13.3, fat:17.8, carbs:31.8, fiber:4.9, salt:1.0, category:"Plats préparés" },
  { name: "Shawarma (poulet)",         aliases: ["shawarma","chawarma"],
    kcal:225, protein:17.0, fat:8.5,  carbs:22.0, fiber:1.5, salt:1.2, category:"Plats préparés" },
  { name: "Paella (poulet-fruits mer)",aliases: ["paella"],
    kcal:165, protein:11.0, fat:5.0,  carbs:20.0, fiber:1.0, salt:1.0, category:"Plats préparés" },
  { name: "Tajine (poulet-citron)",    aliases: ["tajine","tagine"],
    kcal:148, protein:14.0, fat:6.5,  carbs:9.5,  fiber:2.0, salt:0.8, category:"Plats préparés" },
  { name: "Couscous royal (plat)",     aliases: ["couscous royal","plat couscous"],
    kcal:185, protein:11.0, fat:7.5,  carbs:20.0, fiber:2.5, salt:1.0, category:"Plats préparés" },
  { name: "Bolognese (sauce)",         aliases: ["bolognese","bolognaise","sauce bolognaise"],
    kcal:115, protein:8.5,  fat:6.5,  carbs:7.0,  fiber:1.5, salt:0.6, category:"Plats préparés" },
  { name: "Moussaka",                  aliases: ["moussaka","mousaka"],
    kcal:186, protein:9.0,  fat:12.0, carbs:12.0, fiber:2.0, salt:0.7, category:"Plats préparés" },
  { name: "Spring rolls (frits)",      aliases: ["spring rolls","nems","rouleau printemps"],
    kcal:210, protein:6.5,  fat:10.5, carbs:24.5, fiber:1.5, salt:0.7, category:"Plats préparés" },
  { name: "Pad thaï",                  aliases: ["pad thai","pad thaï","phat thai"],
    kcal:183, protein:9.5,  fat:6.5,  carbs:23.5, fiber:1.5, salt:0.8, category:"Plats préparés" },
  { name: "Ramen (soupe nouilles)",    aliases: ["ramen","soupe ramen","nouilles ramen"],
    kcal:97,  protein:6.5,  fat:2.5,  carbs:13.5, fiber:1.0, salt:1.2, category:"Plats préparés" },
  { name: "Soupe miso",                aliases: ["soupe miso","miso soup","miso"],
    kcal:40,  protein:2.5,  fat:1.5,  carbs:4.5,  fiber:1.0, salt:1.1, category:"Plats préparés" },
  { name: "Samosa (légumes, frit)",    aliases: ["samosa","samoussas","samoussa"],
    kcal:262, protein:5.5,  fat:13.0, carbs:31.5, fiber:2.5, salt:0.8, category:"Plats préparés" },
  { name: "Taco (boeuf)",              aliases: ["taco","tacos"],
    kcal:218, protein:11.0, fat:9.5,  carbs:24.0, fiber:2.0, salt:1.1, category:"Plats préparés" },
  { name: "Pizza 4 fromages",          aliases: ["pizza 4 fromages","pizza fromages","quattro formaggi"],
    kcal:285, protein:13.5, fat:12.5, carbs:31.0, fiber:2.0, salt:1.8, category:"Plats préparés" },
  { name: "Pizza reine (jambon-champignons)",aliases: ["pizza reine","pizza jambon","pizza champignon"],
    kcal:248, protein:12.0, fat:9.5,  carbs:30.0, fiber:2.0, salt:1.5, category:"Plats préparés" },
];

/**
 * Search local DB — returns matching foods (normalized, accent-insensitive)
 */
function searchLocalDB(query) {
  const normalize = s => s.toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9 ]/g, " ").trim();
  const q = normalize(query);
  const words = q.split(/\s+/).filter(w => w.length > 1);

  return FOODS_DB.filter(food => {
    return food.aliases.some(alias => {
      const a = normalize(alias);
      return words.some(w => a.includes(w)) || a.includes(q);
    });
  }).sort((a, b) => {
    // exact alias match first
    const aN = normalize(a.name);
    const bN = normalize(b.name);
    const qa = aN.includes(q) ? 0 : 1;
    const qb = bN.includes(q) ? 0 : 1;
    return qa - qb;
  });
}
